apiVersion: apps/v1
kind: Deployment
metadata:
  name: afristocks-backend
  namespace: afristocks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: afristocks-backend
  template:
    metadata:
      labels:
        app: afristocks-backend
    spec:
      containers:
        - name: afristocks-backend
          image: 771237845610.dkr.ecr.eu-west-1.amazonaws.com/afristocks-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: afristocks-secrets
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: afristocks-secrets
                  key: jwt-secret
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: afristocks-secrets
                  key: redis-password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: afristocks-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: afristocks-secrets
                  key: aws-secret-access-key
            - name: ORANGE_MONEY_KEY
              valueFrom:
                secretKeyRef:
                  name: afristocks-secrets
                  key: orange-money-key
            - name: MTN_MOMO_KEY
              valueFrom:
                secretKeyRef:
                  name: afristocks-secrets
                  key: mtn-momo-key
            - name: WAVE_KEY
              valueFrom:
                secretKeyRef:
                  name: afristocks-secrets
                  key: wave-key

