image: node:20

default:
  before_script:
    - if [ -f backend/package.json ]; then cd backend; fi

variables:
  NODE_ENV: "production"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .npm/
    - node_modules/
    - backend/.npm/
    - backend/node_modules/

install_backend:
  stage: install
  script:
    - npm ci
    - npx prisma generate

build_backend:
  stage: build
  needs: ["install_backend"]
  script:
    - npm run build

test_backend:
  stage: test
  needs: ["build_backend"]
  script:
    - npm test -- --ci --watchAll=false || echo "No tests to run"
  allow_failure: true


