image: node:20

default:
  before_script:
    - cd backend

variables:
  NODE_ENV: "production"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/backend/.npm"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - backend/.npm/
    - backend/node_modules/

.install_backend:
  stage: install
  script:
    - npm ci
    - npx prisma generate
  artifacts:
    expire_in: 1 week
    paths:
      - backend/node_modules/

build_backend:
  stage: build
  needs: [".install_backend"]
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - backend/dist/

test_backend:
  stage: test
  needs: ["build_backend"]
  script:
    - npm test -- --ci --watchAll=false || echo "No tests to run"
  allow_failure: true


