apiVersion: v1
kind: Service
metadata:
  name: afristocks
  namespace: afristocks
spec:
  selector:
    app: afristocks-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # adapte si ton app écoute sur un autre port
