# security/fail2ban/jail.local
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 10.0.0.0/8
bantime = 3600
findtime = 600
maxretry = 5
backend = systemd

[nginx-noscript]
enabled = true
port = http,https
filter = nginx-noscript
logpath = /var/log/nginx/access.log
maxretry = 3

[nginx-login]
enabled = true
port = http,https
filter = nginx-login
logpath = /var/log/nginx/login.log
maxretry = 3
bantime = 7200

[nginx-req-limit]
enabled = true
port = http,https
filter = nginx-req-limit
logpath = /var/log/nginx/*error.log
maxretry = 10
findtime = 60
bantime = 7200

[nginx-badbots]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/nginx/access.log
maxretry = 1
bantime = 86400

[nginx-4xx]
enabled = true
port = http,https
filter = nginx-4xx
logpath = /var/log/nginx/access.log
maxretry = 50
findtime = 300
bantime = 3600

[docker-nginx]
enabled = true
filter = docker-nginx
logpath = /var/lib/docker/containers/*/*-json.log
maxretry = 5
bantime = 3600